---
- name: Get IOS router configuration
  ios_command:
    commands:
      - show run
  register: output

- name: Print IOS router configuration
  debug: var=output.stdout_lines

- name: Call ios_parser.py
  become: true
  become_user: root
  command: python3 {{ admin_configs['parsers_paths']['ios_parser'] }} {{ admin_configs['tmp_config_file_path'] }} '{{ output.stdout[0] }}' {{ admin_configs['bgp_results_path'] }}




