#
# ARTEMIS Configuration File
#

# Start of Prefix Definitions
prefixes:
  prefix_0: &prefix_0
  - 10.1.0.0/16
  prefix_1: &prefix_1
  - 130.10.1.0/24
  prefix_2: &prefix_2
  - 130.10.1.0/26
  prefix_3: &prefix_3
  - 130.10.1.64/26
# End of Prefix Definitions

# Start of Monitor Definitions
monitors:
  riperis:
  - ''
  bgpstreamlive:
  - routeviews
  - ris
  betabmp:
  - betabmp
  exabgp:
  - ip: exabgp
    port: 5000
# End of Monitor Definitions

# Start of ASN Definitions
asns:
  CUSTOMER: &CUSTOMER
  - 64801
  PEER: &PEER
  - 65312
  UPSTREAM: &UPSTREAM
  - 64712
  AS_64601: &AS_64601
  - 64601
  AS_65001: &AS_65001
  - 65001
  AS_65002: &AS_65002
  - 65002
  AS_65010: &AS_65010
  - 65010
# End of ASN Definitions

# Start of Rule Definitions
rules:
- prefixes:
  - *prefix_0
  origin_asns:
  - *AS_65001
  neighbors:
  - *AS_64601
  - *UPSTREAM
  - *CUSTOMER
  - *AS_65010
  - *PEER
  mitigation: /root/mitigation_trigger.py
- prefixes:
  - *prefix_1
  - *prefix_2
  - *prefix_3
  origin_asns:
  - *AS_65001
  neighbors:
  - *AS_65002
  - *AS_65010
  mitigation: /root/mitigation_trigger.py
# End of Rule Definitions
