#
# ARTEMIS Configuration File (default config, please change in your deployment)
#
# Defining a named variable:
#     named_variable: &named_variable
#         value_of_variable
# Use named variable:
#     *named_variable
# - denotes an entry
#
# Start of Prefix Definitions (IPv4 and IPv6 are supported)
prefixes:
    super_prefix: &super_prefix
        - 2.2.0.0/23
# End of Prefix Definitions
#
# Start of Monitor Definitions
monitors:
    #riperis: [''] # by default this uses all available monitors
    #bgpstreamlive:
    #    - routeviews
    #    - ris
    #betabmp:
    #    - betabmp
    exabgp:
        - ip: 192.168.10.2
          port: 5000
    # bgpstreamhist:
    #     - <csv_dir_with_formatted_BGP_updates>
# End of Monitor Definitions
#
# Start of ASN Definitions
asns:
    my_asn: &my_asn
        65001
    my_neighbor: &my_neighbor
        65002
# End of ASN Definitions
#
# Start of Rule Definitions
rules:
- prefixes:
    - *super_prefix
  origin_asns:
    - *my_asn
  neighbors:
    - *my_neighbor
  mitigation:
      manual
# End of Rule Definitions