---
- name: Get IOS router configuration
  ios_command:
    commands:
      - show run
  register: output

- name: Print IOS router configuration
  debug: var=output.stdout_lines

- name: Print IOS BGP configuration as json
  vars:
    path: "{{ admin_configs['parsers_paths']['ios_parser'] }}"
    json_bgp: "{{ output.stdout[0] | parse_cli(path) }}"
  debug: msg="{{ json_bgp }}"

- name: Copy json BGP configuration into file
  vars:
    path: "{{ admin_configs['parsers_paths']['ios_parser'] }}"
    json_bgp: "{{ output.stdout[0] | parse_cli(path) }}"
  lineinfile:
    path: "{{ admin_configs['bgp_results_path'] }}"
    create: yes
    line: "{{ json_bgp | to_json }}"
    mode: '777'