---
- name: Get IOS router configuration
  ios_command:
    commands:
      - show run
  register: output

- name: Print IOS router configuration
  debug: var=output.stdout_lines

- name: Print IOS BGP configuration as json
  vars:
    path: "{{inventory_dir | dirname }}/ansible/parsers/ios_parser.yaml"
    json_bgp: "{{ output.stdout[0] | parse_cli(path) }}"
  debug: msg="{{ json_bgp }}"

- name: Copy json BGP configuration into file
  vars:
    path: "{{inventory_dir | dirname }}/ansible/parsers/ios_parser.yaml"
    json_bgp: "{{ output.stdout[0] | parse_cli(path) }}"
  lineinfile:
    path: "{{inventory_dir | dirname }}/ansible/bgp_config_files/results.json"
    create: yes
    line: "{{ json_bgp | to_json }}"
    mode: '777'

- name: Execute python script
  become: true
  become_user: root
  command: python3 {{inventory_dir | dirname }}/python/conf_generator.py {{inventory_dir | dirname }}/ansible/bgp_config_files/results.json
