---
- name: Get IOS router configuration
  ios_command:
    commands:
      - show run
  register: output

- name: Print IOS router configuration
  debug: var=output.stdout_lines

- name: Print IOS BGP configuration as json
  vars:
    json_bgp: "{{ output.stdout[0] | parse_cli('/home/george/UOC-CSD/Diploma_Thesis/ansible/parsers/ios_parser.yaml') }}"
  debug: msg="{{ json_bgp }}"

- name: Copy json BGP configuration into a file
  vars:
    json_bgp: "{{ output.stdout[0] | parse_cli('/home/george/UOC-CSD/Diploma_Thesis/ansible/parsers/ios_parser.yaml') }}"
  local_action: copy content="{{ json_bgp }}" dest=../bgp_config_files/results.txt

- name: Execute python script
  become: true
  become_user: root
  vars:
    json_bgp: "{{ output.stdout[0] | parse_cli('/home/george/UOC-CSD/Diploma_Thesis/ansible/parsers/ios_parser.yaml') }}"
  command: python3 ../../python/ios_generator.py "\"{{ json_bgp }}\""
