---
- name: Run CISCO commands  
  hosts: CISCO-ROUTERS
  connection: local
  gather_facts: false

  tasks:
    - name: Get BGP configuration
      ios_command: 
        commands:
          - show run 
      register: output

    - debug: var=output.stdout_lines   

    - debug: msg="{{ output.stdout[0] | parse_cli('/etc/ansible/parsers/ios_parser.yaml') }}"

    - local_action: copy content={{ output.stdout[0] | parse_cli('/etc/ansible/parsers/ios_parser.yaml') }} dest=../bgp_config_files/results.txt 
