---
- name: EXECUTE TASKS FOR EACH CONNECTED ROUTER
  hosts: all
  connection: network_cli
  gather_facts: false

  vars:
    admin_configs: "{{ lookup('file', '/root/admin_configs.json') | from_json }}"

  tasks:
    - name: Delete file with json representations
      lineinfile:
        path: "{{ admin_configs['bgp_results_path'] }}"
        state: absent
        regexp: '.*'
        unsafe_writes: yes

    - name: RUN IOS COMMAND's
      include: ios_playbook.yaml
      when: ansible_network_os == 'ios'

    - name: Execute python script to generate artemis configuration file
      become: true
      become_user: root
      command: python3 {{ admin_configs['config_generator_path'] }} /root/admin_configs.json
