---
- name: Run CISCO commands  
  hosts: localhost
  connection: local
  gather_facts: false
 
  vars:
    contents: "\"{{ lookup('file', '../bgp_config_files/results_stable.txt') }}\""

  tasks:
    - debug: msg="{{ contents }}"

    - debug: var=output.stdout_lines   

    - debug: msg="{{ contents | parse_cli('/home/george/UOC-CSD/Diploma_Thesis/ansible/parsers/ios_parser.yaml') }}" 
