---
- name: Print contents
  vars:
    contents: "\"{{ lookup('file', '../bgp_config_files/results_stable.txt') }}\""
  debug: msg="{{ contents }}"

- name: Print Json_bgp
  vars:
    contents: "\"{{ lookup('file', '../bgp_config_files/results_stable.txt') }}\""
    json_bgp: "{{ contents | parse_cli('/home/george/UOC-CSD/Diploma_Thesis/ansible/parsers/ios_parser.yaml') }}"
  debug: msg="{{ json_bgp }}"

- name: Copy json to file
  vars:
    contents: "\"{{ lookup('file', '../bgp_config_files/results_stable.txt') }}\""
    json_bgp: "{{ contents | parse_cli('/home/george/UOC-CSD/Diploma_Thesis/ansible/parsers/ios_parser.yaml') }}"
  lineinfile:
    path: ../bgp_config_files/results.json
    create: yes
    line: "{{ json_bgp | to_json }}"
    mode: '777'


- name: Execute python script
  become: true
  become_user: root
  command: python3 ../../python/conf_generator.py
