---
- name: Print contents
  vars:
    contents: "\"{{ lookup('file', '{{inventory_dir | dirname }}/ansible/bgp_config_files/results_stable.txt') }}\""
  debug: msg="{{ contents }}"

- name: Print Json_bgp
  vars:
    contents: "\"{{ lookup('file', '{{inventory_dir | dirname }}/ansible/bgp_config_files/results_stable.txt') }}\""
    path: "{{inventory_dir | dirname }}/ansible/parsers/ios_parser.yaml"
    json_bgp: "{{ contents | parse_cli(path) }}"
  debug: msg="{{ json_bgp }}"

- name: Copy json to file
  vars:
    contents: "\"{{ lookup('file', '{{inventory_dir | dirname }}/ansible/bgp_config_files/results_stable.txt') }}\""
    path: "{{inventory_dir | dirname }}/ansible/parsers/ios_parser.yaml"
    json_bgp: "{{ contents | parse_cli(path) }}"
  lineinfile:
    path: "{{inventory_dir | dirname }}/ansible/bgp_config_files/results.json"
    create: yes
    line: "{{ json_bgp | to_json }}"
    mode: '777'

- name: Print cwd
  debug: msg="{{inventory_dir | dirname }}"


- name: Execute python script
  become: true
  become_user: root
  command: python3 {{inventory_dir | dirname }}/python/conf_generator.py {{inventory_dir | dirname }}/ansible/bgp_config_files/results.json
