---
- name: EXECUTE TASKS FOR EACH CONNECTED ROUTER
  hosts: '{{ target }}'
  connection: network_cli
  gather_facts: false

  tasks:

    - name: IOS MITIGATION
      include: ios_tunnel_mitigation.yaml
      when: ansible_network_os == 'ios'
