---
vars:
  my_prefixes:
    network: "{{ item.network }}"
    mask: "{{ item.mask }}"
  my_as:
    asn: "{{ item.my_asn }}"
  my_neighbors:
    interface_ip: "{{ item.interface_ip }}"
    asn: "{{ item.asn }}"
  my_peer_groups:
    interface_ip: "{{ item.interface_ip }}"
    asn: "{{ item.peer_group }}"
  my_bgp_router_id:
    router_id: "{{ item.router_id }}"
  my_interfaces:
    interface_name: "{{ item.interface_name }}"
    interface_ip: "{{ item.interface_ip }}"
    interface_mask: "{{ item.interface_mask }}"
  my_routemaps_per_neighbor:
    interface_ip: "{{ item.interface_ip }}"
    routemap_name: "{{ item.routemap_name }}"
    direction: "{{ item.direction }}"

keys:
  prefixes:
    value: "{{ my_prefixes }}"
    items: "[^.]network\\s+(?P<network>\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})\\s+mask\\s+(?P<mask>\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})"
  origin_as:
    value: "{{ my_as }}"
    items: "[^.]router\\s+bgp\\s+(?P<my_asn>\\d+)"
  neighbors:
    value: "{{ my_neighbors }}"
    items: "[^.]neighbor\\s+(?P<interface_ip>\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})\\s+remote-as\\s+(?P<asn>\\d+)"
  peer-groups:
    value: "{{ my_peer_groups }}"
    items: "[^.]neighbor\\s+(?P<interface_ip>\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})\\s+peer-group\\s+(?P<peer_group>\\w+)"
  bgp_router_id:
    value: "{{ my_bgp_router_id }}"
    items: "[^.]bgp\\s+router-id\\s+(?P<router_id>\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})"
  interfaces:
    value: "{{ my_interfaces }}"
    items: "[^.]interface\\s+(?P<interface_name>.+)\\s+ip\\s+address\\s+(?P<interface_ip>\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})\\s+(?P<interface_mask>\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})"
  routemaps_per_neighbor:
    value: "{{ my_routemaps_per_neighbor }}"
    items: "[^.]neighbor\\s+(?P<interface_ip>.+)\\s+route-map(?P<routemap_name>.+)\\s+(?P<direction>.+)"
  routemaps_definitions:
    value: "{{ my_routemaps_definitions }}"
    start_block: "[^.]route-map.+$"
    end_block: "[^.]!$"
    items:
      - "[^.]route-map\\s+(?P<routemap_name>.+)\\s+(?P<rule>.+)\\s+(?P<sequence_number>.+)"
      - "[^.]match\\s+ip\\s+address\\s+(?P<acl_id_list>.+)"
      - "[^.]match\\s+ip\\s+address\\s+prefix-list\\s+(?P<prefix_list_name>.+)"
