---
vars:
  my_prefixes:
    network: "{{ item.network }}"
    mask: "{{ item.mask }}"
  my_as:
    asn: "{{ item.my_asn }}"
  my_neighbors:
    interface_ip: "{{ item.interface_ip }}"
    asn: "{{ item.asn }}"
  my_peer_groups:
    interface_ip: "{{ item.interface_ip }}"
    asn: "{{ item.peer_group }}"
  my_bgp_router_id:
    router_id: "{{ item.router_id }}"
  my_interfaces:
    interface_name: "{{ item.interface_name }}"
    interface_ip: "{{ item.interface_ip }}"
    interface_mask: "{{ item.interface_mask }}"

keys:
  prefixes:
    value: "{{ my_prefixes }}"
    items: "[^.]network\\s+(?P<network>\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})\\s+mask\\s+(?P<mask>\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})"
  origin_as:
    value: "{{ my_as }}"
    items: "[^.]router\\s+bgp\\s+(?P<my_asn>\\d+)"
  neighbors:
    value: "{{ my_neighbors }}"
    items: "[^.]neighbor\\s+(?P<interface_ip>\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})\\s+remote-as\\s+(?P<asn>\\d+)"
  peer-groups:
    value: "{{ my_peer_groups }}"
    items: "[^.]neighbor\\s+(?P<interface_ip>\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})\\s+peer-group\\s+(?P<peer_group>\\w+)"
  bgp_router_id:
    value: "{{ my_bgp_router_id }}"
    items: "[^.]bgp\\s+router-id\\s+(?P<router_id>\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})"
  interfaces:
    value: "{{ my_interfaces }}"
    items: "[^.]interface\\s+(?P<interface_name>.+)\\s+ip\\s+address\\s+(?P<interface_ip>\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})\\s+(?P<interface_mask>\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})"